sudo: required
services:
  - docker

before_install:
  - docker build -t almostfamiliar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run almostfamiliar/react-test npm test -- --coverage

after_success:
  - docker build -t almostfamiliar/multi-docker-client  ./client
  - docker build -t almostfamiliar/multi-docker-nginx  ./nginx
  - docker build -t almostfamiliar/multi-docker-server  ./server
  - docker build -t almostfamiliar/multi-docker-worker  ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push almostfamiliar/multi-docker-client
  - docker push almostfamiliar/multi-docker-nginx
  - docker push almostfamiliar/multi-docker-server
  - docker push almostfamiliar/multi-docker-worker


deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: multi-docker-app
  env: MultiDockerApp-env
  bucket_name: elasticbeanstalk-eu-central-1-286163547114
  bucket_path: multi-docker-app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"