sudo: required
services:
  - docker

before_install:
  - docker build -t almostfamiliar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run almostfamiliar/react-test npm test -- --coverage

after_success:
  - docker build -t almostfamiliar/multi-docker-client  ./client
  - docker build -t almostfamiliar/multi-docker-nginx  ./nginx
  - docker build -t almostfamiliar/multi-docker-server  ./server
  - docker build -t almostfamiliar/multi-docker-worker  ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push almostfamiliar/multi-docker-client
  - docker push almostfamiliar/multi-docker-nginx
  - docker push almostfamiliar/multi-docker-server
  - docker push almostfamiliar/multi-docker-worker